// Define los códigos de error y el mapeo en el mismo archivo

import { ErrorCategories } from "../events/types/instituciones-pagos";

export const errorCodes: { [key: string]: string } = {
 "E000": "Ejecucion satisfactoria",
 "E001": "Clave incorrecta",
 "E002": "Por favor verifique el parametro de consulta",
 "E003": "El usuario o placa tiene titulos de credito pendientes, debe realizar el tramite en las oficinas de la EMOV EP en Tesoreria",
 "E004": "La placa del vehiculo se encuentra en un titulo de credito, debe realizar el tramite en las oficinas de la EMOV EP en Tesoreria",
 "E005": "No hay valores pendientes de pago",
 "E006": "Revisar el valor que se envia en el usuario recaudador",
 "E007": "Revisar el valor que se envia en el establecimiento",
 "E008": "Revisar el codigo del establecimiento enviado",
 "E009": "Revisar el valor que se envia en el numero de transaccion",
 "E010": "El numero de transacción enviado, ya consta como recaudado",
 "E011": "No hay rubros manuales a recaudar", //CAMBIO
 "E012": "El valor a cobrar por RTV no es el mismo enviado en la consulta",
 "E013": "El valor a cobrar por infracciones de control en vía pública no es el mismo enviado en la consulta",
 "E014": "El valor a cobrar por centro de retención vehicular no es el mismo enviado en la consulta",
 "E015": "El valor a cobrar por certificado de no adeudar no es el mismo enviado en la consulta",
 "E016": "El valor a cobrar por cartera en general no es el mismo enviado en la consulta",
 "E017": "El valor a cobrar por infracciones de tránsito no es el mismo enviado en la consulta",
 "E018": "El valor a cobrar por multas de sellaje no es el mismo enviado en la consulta",
 "E019": "Nro. de lote del servicio RTV no existe o ya fue recaudado",
 "E020": "Nro. de lote del servicio CVP no existe o ya fue recaudado",
 "E021": "Nro. de lote del servicio PRV no existe o ya fue recaudado",
 "E022": "Nro. de lote del servicio CER no existe o ya fue recaudado",
 "E023": "Nro. de lote del servicio CXC no existe o ya fue recaudado",
 "E024": "Nro. de lote del servicio CIT no existe o ya fue recaudado",
 "E025": "Nro. de lote del servicio MSE no existe o ya fue recaudado",
 "E026": "Revise el detalle de recaudación manual",
 "E027": "Total de recaudación manual no es igual al total detalle",
 "E028": "No se ha enviado el documento de identificacion del usuario",
 "E029": "El formato de identificación del usuario no es valido",
 "E030": "No se ha enviado el tipo de identificacion del usuario",
 "E031": "Revisar tipo documento de usuario valores validos: “CED”, “PAS”, “RUC”",
 "E032": "No se ha enviado los nombres y/o apellidos del usuario",
 "E033": "No se ha enviado",
 "E034": "No se ha enviado el telefono del usuario",
 "E035": "No se ha enviado la direccion del usuario",
 "E036": "No se ha enviado el correo electrónico del usuario",
 "E037": "Revisar el correo electronico enviado",
 "E038": "Debe enviarse para el cobro del rubro CVP y PRV juntos",
 "E039": "Revisar el numero de ítem enviado",
 "E040": "Revisar el precio del item enviado",
 "E041": "No se puede emitir el Certificado de no Adeudar porque tiene multas pendientes por el rubro CVP",
 "E042": "No se puede emitir el Certificado de no Adeudar porque tiene multas pendientes por el rubro PRV",
 "E043": "No se puede emitir el Certificado de no Adeudar porque tiene multas pendientes por el rubro MSE",
 "E044": "No se puede emitir el Certificado de no Adeudar porque tiene multas pendientes por el rubro CIT",
 "E045": "Revisar el usuario que reversa",
 "E046": "Revisar el usuario que aprueba el reverso",
 "E047": "Revisar el nro. de transacción para el reverso",
 "E048": "El número de transacción enviada ya ha sido reversada",
 "E049": "Revisar que la recaudacion se realizo el mismo dia en el que se solicita el reverso",
 "E050": "No hay rubros a reversar",
 "E051": "Vehiculo ya salio del CRV no es posible reversar la transaccion",
 "E052": "No es posible reversar los valores por RTV, no se puede reversar la transaccion",
 "E053": "Revisar el valor que se envía en el lote del rubro OTR",
 "E054": "Revisar nro. de lote del rubro OTR",
 "E055": "No es posible reversar el cobro, la Orden de Pago no se encuentra en estado \"ESPERA\"",
 "E056": "Revisar el valor que se envía en el lote del rubro ORD",
 "E057": "No se puede emitir el Certificado de no Adeudar porque tiene multas pendientes por el rubro ORD",
 "E058": "Revisar nro. de lote del rubro ORD",
 "E099": "No se ejecutó correctamente la recaudación",

 "M001": "Error al cancelar Rubros",
 "M002": "Error al reversar Rubros",
 "M003": "No se encuentra la orden de pago",
 "M004": "No se puede procesar una orden que fue cancelada/reversada",
 "M005": "Error en los parametros de la orden",
 "M006": "Error al actualizar la orden de pago",
 "M007": "Error al inicializar base de datos",
 "M008": "No se encuentra el pago",
 "M009": "No se puede reversar una deuda no pagada",
 "M010": "No se puede procesar una orden que ya fue pagada",
 "M011": "Error al consultar Rubros",
 "M012": "La Consulta se realizo con exito",
 "M013": "API Key de Middleware Invalida",
 "M014": "Error al generar comprobante de pago",
 "M015": "Error al obtener Total Pagado",
 "M016": "Error al obtener Comprobante de una orden no pagada/reversada",
 "M017": "No se puede cancelar una orden pagada/reversada",
 "M018": "Error al obtener total de rubros en consultas",
 "M019": "No se puede emitir el certificado de no adeudar debido a que el vehículo tiene deudas pendientes.",
 "M020": "En esta categoria debe pagar todas las deudas pendientes. Agregue todos los rubros a la orden de pago.",
 "M021": "La Orden de pago solo debe contener el rubro: certificado de no adeudar (CER).",
 "M022": "Error al crear orden de pago",
 "M023": "Error en el servicio externo de parqueo Tarifado (APP-SERT)",
 "M024": "Usuario no registrado o codigo de consulta incorrecto",
 //confirmapago
 "PAG": "Ejecucion satisfactoria",
 "TRAN": "Transaccion no registrada, Existe una solicitud de pago en el mismo día para el identificador de deuda ya confirmada(PAG)",
 "TCOMP": "Transaccion ya comprobada",
 "ERRING": "Transaccion no puede comprobar registro porque existió un error en la transaccion al ingreso",
 "NOTC": "Transacción no puede ser comprobada porque existe pendiente de comprobacion una nota de credito",
 "MON": "El valor de monto no coincide",
 "CTA": "El valor de la cuenta bancaria no coincide",
 "INST": "El código de Instalacion no existe en la base maestra",
 "AUT": "No tiene autorizacion",
 "REV": "Reversado",
 "REVERSED": "Reversado",
 "ECAN": "Canal transaccional enviado no existe",
 //solpago
 "ING": "Se ha realizado la solicitud satisfactoriamente",
 "FPAG": "Existe fecha de pago para el mes actual, el pago no procede, Solicitud de pago duplicada para la misma fecha-hora",
 "DEB": "El pago se realiza por debito en la cuenta de Entidad Externa",
 "BANE": "El pago ya se registro como pagado por Banca Electronica",
 "MPAG": "El pago no corresponde con el monto adeudado para esa instalacion",
 "SMAN": "Sistema en mantenimiento.",
 "EMI": "Deuda esta siendo emitida, consultar luego",
 "CLIR": "Cliente tiene restricciones de corbo",
 "PPAG": "Pago en proceso Banca Electronica",

 //consultas
 "OK": "La Consulta se realizo con exito",
 "ERROR": "Se produjo un error al realizar la consulta",
 "TINS": "Tipo de Instalación no coincide con identificador de la deuda",

 //reversoEtapa

 "OK200": "El pago de la deuda ha sido reversado con éxito",
 "ERR02": "Error al reversar el pago de la deuda, consulte con Recaudación",
 "ERR03": "Error al reversar el pago de la deuda, consulte con Recaudación",
 "ERR11": "Los parámetros especificados para el reverso son incorrectos",
 "ERR12": "La transacción ya fue reversada",
 "ERR13": "La transacción no se encuentra pagada",
 "ERR14": "No se encuentran los parámetros de configuración requeridos, consulte con Recaudación",
 "ERR15": "El número de la transacción no es correcto",
 "ERR16": "El pago no tiene un documento asociado",
 "ERR17": "No se puede reversar un pago contabilizado",
 "ERR18": "No se puede reversar un pago de [desde] a [hasta], excepto [días]",
 "ERR31": "La entidad bancaria no está habilitada para realizar reversos",
 "ERR32": "La entidad bancaria no tiene permisos habilitados",
 "ERR33": "La entidad bancaria no tiene habilitado el permiso para reversos",

 //Errores genrales
 'ECONNABORTED': 'La solicitud ha superado el tiempo de espera. Inténtelo de nuevo más tarde.',
 'ECONNREFUSED': 'No se pudo conectar al servidor. Verifique su conexión y vuelva a intentarlo.',
 'ENOTFOUND': 'No se pudo encontrar el servidor. Verifique la URL e inténtelo de nuevo.',
 'EHOSTUNREACH': 'El servidor esta inalcanzable. Verifique su red e intente nuevamente.',
 '500': 'Hubo un error en el servidor. Intentelo más tarde.',
 '404': 'No se encontro el recurso solicitado.',
 '401': 'No tiene autorizacion para acceder a este recurso.',
 '400': 'La solicitud esta mal formada o contiene datos inválidos.',
 "ERR_BAD_REQUEST": "La solicitud está mal formada o contiene datos invalidos.",
 "ERR_NETWORK": "Hubo un problema de conexión con la red.",
 "ERR_BAD_RESPONSE": "El servidor respondio, pero la respuesta no fue valida.",
 "ERR_TIMEOUT": "La solicitud tomo demasiado tiempo para completarse",
 "ERR_CANCELED": "La solicitud fue cancelada antes de completarse.",

 //Errores Especificos PARA EL USURIO
 "MIDDLEWARE": "Error interno de Sistema. Inténtelo nuevamente más tarde.",
 "USER": "",
 "SINTAX": "Hemos encontrado un problema al procesar su solicitud. Inténtelo nuevamente más tarde.",
 "SUCCESS": "",
};

export const statusCodeMapping: { [key: string]: string } = {
 "E000": "SUCCESS",
 "E001": "ERROR",
 "E002": "ERROR",
 "E003": "ERROR",
 "E004": "ERROR",
 "E005": "SUCCESS",
 "E006": "ERROR",
 "E007": "ERROR",
 "E008": "ERROR",
 "E009": "ERROR",
 "E010": "ERROR",
 "E011": "ERROR",
 "E012": "ERROR",
 "E013": "ERROR",
 "E014": "ERROR",
 "E015": "ERROR",
 "E016": "ERROR",
 "E017": "ERROR",
 "E018": "ERROR",
 "E019": "ERROR",
 "E020": "ERROR",
 "E021": "ERROR",
 "E022": "ERROR",
 "E023": "ERROR",
 "E024": "ERROR",
 "E025": "ERROR",
 "E026": "ERROR",
 "E027": "ERROR",
 "E028": "ERROR",
 "E029": "ERROR",
 "E030": "ERROR",
 "E031": "ERROR",
 "E032": "ERROR",
 "E033": "ERROR",
 "E034": "ERROR",
 "E035": "ERROR",
 "E036": "ERROR",
 "E037": "ERROR",
 "E038": "ERROR",
 "E039": "ERROR",
 "E040": "ERROR",
 "E041": "ERROR",
 "E042": "ERROR",
 "E043": "ERROR",
 "E044": "ERROR",
 "E045": "ERROR",
 "E046": "ERROR",
 "E047": "ERROR",
 "E048": "ERROR",
 "E049": "ERROR",
 "E050": "ERROR",
 "E051": "ERROR",
 "E052": "ERROR",
 "E053": "ERROR",
 "E054": "ERROR",
 "E055": "ERROR",
 "E056": "ERROR",
 "E057": "ERROR",
 "E058": "ERROR",
 "E099": "ERROR",
 "M001": "ERROR",
 "M002": "ERROR",
 "M003": "ERROR",
 "M004": "ERROR",
 "M005": "ERROR",
 "M006": "ERROR",
 "M007": "ERROR",
 "M008": "ERROR",
 "M009": "ERROR",
 "M010": "ERROR",
 "M011": "ERROR",
 "M012": "SUCCESS",
 "M013": "ERROR",
 "M014": "ERROR",
 "M015": "ERROR",
 "M016": "ERROR",
 "M017": "ERROR",
 "M018": "ERROR",
 "M019": "ERROR",
 "M020": "ERROR",
 "M021": "ERROR",
 "M022": "ERROR",
 "M023": "ERROR",
 "M024": "SUCCESS",

 //confirmaPagoEtapa
 "PAG": "SUCCESS",
 "TRAN": "ERROR",
 "TCOMP": "SUCCESS",
 "ERRING": "ERROR",
 "NOTC": "ERROR",
 "MON": "ERROR",
 "CTA": "ERROR",
 "INST": "ERROR",
 "AUT": "ERROR",
 "REV": "SUCCESS",
 "REVERSED": "SUCCESS",
 "ECAN": "ERROR",
 //solpagoEtapa
 "ING": "SUCCESS",
 "FPAG": "ERROR",
 "DEB": "ERROR",
 "BANE": "ERROR",
 "MPAG": "ERROR",
 "SMAN": "ERROR",
 "EMI": "ERROR",
 "CLIR": "ERROR",
 "PPAG": "ERROR",

 //MUNI
 "MUNI001": "SUCCESS",
 "MUNI002": "ERROR",

 //consultas
 "OK": "SUCCESS",
 "ERROR": "ERROR",
 "TINS": "ERROR",

 //reverso
 "OK200": "SUCCESS",
 "ERR02": "ERROR",
 "ERR03": "ERROR",
 "ERR11": "ERROR",
 "ERR12": "ERROR",
 "ERR13": "ERROR",
 "ERR14": "ERROR",
 "ERR15": "ERROR",
 "ERR16": "ERROR",
 "ERR17": "ERROR",
 "ERR18": "ERROR",
 "ERR31": "ERROR",
 "ERR32": "ERROR",
 "ERR33": "ERROR",
 //errores generales
 'ECONNABORTED': "ERROR",
 'ECONNREFUSED': "ERROR",
 'ENOTFOUND': "ERROR",
 'EHOSTUNREACH': "ERROR",
 '500': "ERROR",
 '404': "ERROR",
 '401': "ERROR",
 '400': "ERROR",
 "ERR_BAD_REQUEST": "ERROR",
 "ERR_NETWORK": "ERROR",
 "ERR_BAD_RESPONSE": "ERROR",
 "ERR_TIMEOUT": "ERROR",
 "ERR_CANCELED": "ERROR",

 "MIDDLEWARE": "ERROR",
 "USER": "ERROR",
 "SINTAX": "ERROR",
 "SUCCESS": "SUCCESS",
};

export const httpStatusCodes: { [key: string]: number } = {
 "E000": 200,
 "E001": 401,
 "E002": 400,
 "E003": 409,
 "E004": 409,
 "E005": 200,
 "E006": 400,
 "E007": 400,
 "E008": 400,
 "E009": 400,
 "E010": 409,
 "E011": 200,
 "E012": 400,
 "E013": 400,
 "E014": 400,
 "E015": 400,
 "E016": 400,
 "E017": 400,
 "E018": 400,
 "E019": 409,
 "E020": 409,
 "E021": 409,
 "E022": 409,
 "E023": 409,
 "E024": 409,
 "E025": 409,
 "E026": 400,
 "E027": 400,
 "E028": 400,
 "E029": 400,
 "E030": 400,
 "E031": 400,
 "E032": 400,
 "E033": 400,
 "E034": 400,
 "E035": 400,
 "E036": 400,
 "E037": 400,
 "E038": 400,
 "E039": 400,
 "E040": 400,
 "E041": 409,
 "E042": 409,
 "E043": 409,
 "E044": 409,
 "E045": 400,
 "E046": 400,
 "E047": 400,
 "E048": 400,
 "E049": 400,
 "E050": 409,
 "E051": 409,
 "E052": 409,
 "E053": 400,
 "E054": 400,
 "E055": 422,
 "E056": 400,
 "E057": 409,
 "E058": 409,
 "E099": 500,

 "M001": 500,
 "M002": 500,
 "M003": 404,
 "M004": 400,
 "M005": 400,
 "M006": 500,
 "M007": 500,
 "M008": 404,
 "M009": 400,
 "M010": 409,
 "M011": 500,
 "M012": 200,
 "M013": 401,
 "M014": 500,
 "M015": 500,
 "M016": 400,
 "M017": 400,
 "M018": 500,
 "M019": 500,
 "M020": 500,
"M021": 500,
"M022": 500,
"M023": 500,
"M024": 200,


 "PAG": 200,
 "TRAN": 409,
 "TCOMP": 409,
 "ERRING": 500,
 "NOTC": 409,
 "MON": 400,
 "CTA": 400,
 "INST": 404,
 "AUT": 401,
 "REV": 409,
 "REVERSED": 409,
 "ECAN": 400,

 "ING": 200,
 "FPAG": 409,
 "DEB": 200,
 "BANE": 409,
 "MPAG": 400,
 "SMAN": 503,
 "EMI": 202,
 "CLIR": 403,
 "PPAG": 202,

 "OK": 200,
 "ERROR": 500,
 "TINS": 400,

 "OK200": 200,
 "ERR02": 500,
 "ERR03": 500,
 "ERR11": 400,
 "ERR12": 409,
 "ERR13": 409,
 "ERR14": 500,
 "ERR15": 400,
 "ERR16": 400,
 "ERR17": 400,
 "ERR18": 400,
 "ERR31": 403,
 "ERR32": 403,
 "ERR33": 403,

 "ECONNABORTED": 408,
 "ECONNREFUSED": 503,
 "ENOTFOUND": 404,
 "EHOSTUNREACH": 503,
 "500": 500,
 "404": 404,
 "401": 401,
 "400": 400,
 "ERR_BAD_REQUEST": 400,
 "ERR_NETWORK": 503,
 "ERR_BAD_RESPONSE": 502,
 "ERR_TIMEOUT": 408,
 "ERR_CANCELED": 499
}

export const httpStatusCodesTypes: { [key: string]: string } = {
 "E000": ErrorCategories.SUCCESS,
 "E001": ErrorCategories.MIDDLEWARE,
 "E002": ErrorCategories.USER,
 "E003": ErrorCategories.USER,
 "E004": ErrorCategories.USER,
 "E005": ErrorCategories.USER,
 "E006": ErrorCategories.MIDDLEWARE,
 "E007": ErrorCategories.MIDDLEWARE,
 "E008": ErrorCategories.MIDDLEWARE,
 "E009": ErrorCategories.MIDDLEWARE,
 "E010": ErrorCategories.MIDDLEWARE,
 "E011": ErrorCategories.USER,
 "E012": ErrorCategories.SINTAX,
 "E013": ErrorCategories.SINTAX,
 "E014": ErrorCategories.SINTAX,
 "E015": ErrorCategories.SINTAX,
 "E016": ErrorCategories.SINTAX,
 "E017": ErrorCategories.SINTAX,
 "E018": ErrorCategories.SINTAX,
 "E019": ErrorCategories.SINTAX,
 "E020": ErrorCategories.SINTAX,
 "E021": ErrorCategories.SINTAX,
 "E022": ErrorCategories.SINTAX,
 "E023": ErrorCategories.SINTAX,
 "E024": ErrorCategories.SINTAX,
 "E025": ErrorCategories.SINTAX,
 "E026": ErrorCategories.USER,
 "E027": ErrorCategories.SINTAX,
 "E028": ErrorCategories.SINTAX,
 "E029": ErrorCategories.SINTAX,
 "E030": ErrorCategories.SINTAX,
 "E031": ErrorCategories.SINTAX,
 "E032": ErrorCategories.SINTAX,
 "E033": ErrorCategories.SINTAX,
 "E034": ErrorCategories.SINTAX,
 "E035": ErrorCategories.SINTAX,
 "E036": ErrorCategories.SINTAX,
 "E037": ErrorCategories.SINTAX,
 "E038": ErrorCategories.USER,
 "E039": ErrorCategories.SINTAX,
 "E040": ErrorCategories.SINTAX,
 "E041": ErrorCategories.USER, 
 "E042": ErrorCategories.USER, 
 "E043": ErrorCategories.USER, 
 "E044": ErrorCategories.USER, 
 "E045": ErrorCategories.MIDDLEWARE,
 "E046": ErrorCategories.MIDDLEWARE,
 "E047": ErrorCategories.MIDDLEWARE,
 "E048": ErrorCategories.USER,
 "E049": ErrorCategories.SINTAX,
 "E050": ErrorCategories.USER,
 "E051": ErrorCategories.USER,
 "E052": ErrorCategories.USER,
 "E053": ErrorCategories.SINTAX,
 "E054": ErrorCategories.SINTAX,
 "E055": ErrorCategories.MIDDLEWARE,
 "E056": ErrorCategories.SINTAX,
 "E057": ErrorCategories.USER,
 "E058": ErrorCategories.SINTAX,
 "E099": ErrorCategories.MIDDLEWARE,

 "M001": ErrorCategories.MIDDLEWARE,
 "M002": ErrorCategories.MIDDLEWARE,
 "M003": ErrorCategories.SINTAX,
 "M004": ErrorCategories.MIDDLEWARE,
 "M005": ErrorCategories.SINTAX,
 "M006": ErrorCategories.MIDDLEWARE,
 "M007": ErrorCategories.MIDDLEWARE,
 "M008": ErrorCategories.SINTAX,
 "M009": ErrorCategories.SINTAX,
 "M010": ErrorCategories.SINTAX,
 "M011": ErrorCategories.MIDDLEWARE,
 "M012": ErrorCategories.SUCCESS,
 "M013": ErrorCategories.MIDDLEWARE,
 "M014": ErrorCategories.MIDDLEWARE,
 "M015": ErrorCategories.MIDDLEWARE,
 "M016": ErrorCategories.SINTAX,
 "M017": ErrorCategories.SINTAX,
 "M018": ErrorCategories.MIDDLEWARE,
 "M019": ErrorCategories.MIDDLEWARE,
 "M020": ErrorCategories.MIDDLEWARE,
 "M021": ErrorCategories.MIDDLEWARE,
 "M022": ErrorCategories.MIDDLEWARE,
 "M023": ErrorCategories.MIDDLEWARE,
 "M024": ErrorCategories.USER,

 //confirmapago
 "PAG": ErrorCategories.SUCCESS,
 "TRAN": ErrorCategories.USER,
 "TCOMP": ErrorCategories.MIDDLEWARE,
 "ERRING": ErrorCategories.MIDDLEWARE,
 "NOTC": ErrorCategories.MIDDLEWARE,
 "MON": ErrorCategories.SINTAX,
 "CTA": ErrorCategories.MIDDLEWARE,
 "INST": ErrorCategories.SINTAX,
 "AUT": ErrorCategories.MIDDLEWARE,
 "REV": ErrorCategories.SUCCESS,
 "REVERSED": ErrorCategories.SUCCESS,
 "ECAN": ErrorCategories.MIDDLEWARE,

 //SOLpago
 "ING": ErrorCategories.SUCCESS,
 "FPAG": ErrorCategories.USER,
 "DEB": ErrorCategories.USER,
 "BANE": ErrorCategories.USER,
 "MPAG": ErrorCategories.SINTAX,
 "SMAN": ErrorCategories.MIDDLEWARE,
 "EMI": ErrorCategories.USER,
 "CLIR": ErrorCategories.USER,
 "PPAG": ErrorCategories.USER,

 //consultas
 "OK": ErrorCategories.SUCCESS,
 "ERROR": ErrorCategories.MIDDLEWARE,
 "TINS": ErrorCategories.SINTAX,

 //REERSO
 "OK200": ErrorCategories.SUCCESS,
 "ERR02": ErrorCategories.MIDDLEWARE,
 "ERR03": ErrorCategories.MIDDLEWARE,
 "ERR11": ErrorCategories.SINTAX,
 "ERR12": ErrorCategories.SINTAX,
 "ERR13": ErrorCategories.SINTAX,
 "ERR14": ErrorCategories.MIDDLEWARE,
 "ERR15": ErrorCategories.MIDDLEWARE,
 "ERR16": ErrorCategories.MIDDLEWARE,
 "ERR17": ErrorCategories.SINTAX,
 "ERR18": ErrorCategories.SINTAX,
 "ERR31": ErrorCategories.MIDDLEWARE,
 "ERR32": ErrorCategories.MIDDLEWARE,
 "ERR33": ErrorCategories.MIDDLEWARE,

 "ECONNABORTED": ErrorCategories.MIDDLEWARE,
 "ECONNREFUSED": ErrorCategories.MIDDLEWARE,
 "ENOTFOUND": ErrorCategories.MIDDLEWARE,
 "EHOSTUNREACH": ErrorCategories.MIDDLEWARE,
 "500": ErrorCategories.MIDDLEWARE,
 "404": ErrorCategories.MIDDLEWARE,
 "401": ErrorCategories.MIDDLEWARE,
 "400": ErrorCategories.SINTAX,
 "ERR_BAD_REQUEST": ErrorCategories.MIDDLEWARE,
 "ERR_NETWORK": ErrorCategories.MIDDLEWARE,
 "ERR_BAD_RESPONSE": ErrorCategories.MIDDLEWARE,
 "ERR_TIMEOUT": ErrorCategories.MIDDLEWARE,
 "ERR_CANCELED": ErrorCategories.MIDDLEWARE,
}

export class ErrorController {
 static getGeneralStatus(apiStatusCode: string): string {
  return statusCodeMapping[apiStatusCode] || "ERROR";
 }

 static getErrorMessage(apiStatusCode: string): string {
  return errorCodes[apiStatusCode] || "Error al procesar la solicitud";
 }

 static getErrorCodes(apiStatusCode: string): string {
  return errorCodes[apiStatusCode];
 }

 static gethttpStatusCodes(apiStatusCode: string): number {
  return httpStatusCodes[apiStatusCode];
 }

 static gethttpStatusCodesTypes(apiStatusCode: string): string {
  return httpStatusCodesTypes[apiStatusCode] || ErrorCategories.MIDDLEWARE;
 }
}

